// A generic type for your API's successful response structure.
// Using a generic <T> allows us to reuse this for any data type.
export interface SuccessResponse<T> {
  success: true;
  data: T;
  message: string;
}

// Define the possible statuses for an appointment for better type safety.
export type AppointmentStatus = 'scheduled' | 'completed' | 'cancelled';

// Interface for a single Appointment object based on your API response.
export interface Appointment {
  id: string;
  patientName: string;
  age: number;
  symptoms: string;
  appointmentTime: string; // ISO date string
  status: AppointmentStatus;
  doctorId: string;
  createdAt: string; // ISO date string
  updatedAt: string; // ISO date string
}

// Interface for a single Prescription object.
export interface Prescription {
  id: string;
  appointmentId: string;
  medicineName: string;
  dosage: string;
  instructions: string;
  createdAt: string; // ISO date string
  doctorId: string;
}

// A helper type for creating a new prescription.
// It omits fields that are generated by the server.
export type NewPrescription = Omit<Prescription, 'id' | 'createdAt' | 'doctorId'>;